apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  namespace: daksh-portfolio
  labels:
    app: backend
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: daksh-portfolio-backend
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort | default 4000 }}
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongouri-secret
              key: MONGODB_URI