apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: daksh-portfolio
spec:
  selector:
    app: backend
  ports:
    - protocol: {{ .Values.service.protocol | default "TCP" }}
      port: {{ .Values.service.port | default 4000 }}
      targetPort: {{ .Values.service.targetPort | default 4000 }}
  type: {{ .Values.service.type | default "ClusterIP" }}