import { ArrowUpRight, Award, Check, FileText } from 'lucide-react'
import { certs, skills, timeline } from '../data/about'

const About = () => <main className="content-page page-wrap about-page">
  <section className="content-intro about-intro"><div><p className="eyebrow">A little context</p><h1>Engineer by trade,<br /><em>systems thinker</em> by habit.</h1></div><div className="intro-aside"><p>I work at the intersection of cloud infrastructure, reliability engineering, and thoughtful product design. The goal is always the same: make hard things easier to operate.</p><a className="button button-outline resume-link" href="/resume/Daksh-Resume.pdf" target="_blank" rel="noreferrer">Read resume <FileText size={15} /></a></div></section>
  <section className="about-statement"><p className="eyebrow">My point of view</p><p>Good infrastructure should be powerful enough for the edge cases and calm enough for the everyday.</p></section>
  <section className="about-section"><div className="about-section-label"><span>01</span><h2>How I got here</h2></div><div className="timeline-editorial">{timeline.map((item, index) => <article key={`${item.year}-${index}`}><span>{item.year}</span><div><h3>{item.title}</h3><p>{item.description}</p></div></article>)}</div></section>
  <section className="about-section"><div className="about-section-label"><span>02</span><h2>What I bring</h2></div><div className="capability-grid">{['Cloud architecture', 'Reliability & observability', 'DevSecOps delivery', 'Platform thinking'].map((title, index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{['Designing infrastructure that scales without becoming mysterious.', 'Turning telemetry into decisions teams can act on during incidents.', 'Shipping repeatable, secure delivery pipelines with clear guardrails.', 'Building tools that give engineers leverage, not another dashboard.'][index]}</p></article>)}</div></section>
  <section className="about-section"><div className="about-section-label"><span>03</span><h2>Working toolkit</h2></div><div className="skill-cloud">{skills.map((skill, index) => <span key={`${skill}-${index}`}><Check size={13} />{skill}</span>)}</div></section>
  <section className="about-section credentials"><div className="about-section-label"><span>04</span><h2>Credentials</h2></div><div className="credential-list">{certs.map((cert, index) => <a href={cert.link || cert.image || '#'} target="_blank" rel="noreferrer" key={`${cert.title}-${index}`}><Award size={18} /><span>{cert.title}</span><ArrowUpRight size={16} /></a>)}</div></section>
</main>

export default About