import { Check, FileText } from 'lucide-react'
import { skills, timeline } from '../data/about'

const About = () => <main className="content-page page-wrap about-page">
  <section className="content-intro about-intro"><div><p className="eyebrow">A little context</p><h1>Engineer by trade,<br /><em>systems thinker</em> by habit.</h1></div><div className="intro-aside"><p>I teach multicloud systems and build real things that run: resilient infrastructure, automated delivery, observability, and self-healing platforms. The goal is simple: turn complex systems into something useful, understandable, and dependable.</p><a className="button button-outline resume-link" href="/resume/Daksh-Resume.pdf" target="_blank" rel="noreferrer">Read resume <FileText size={15} /></a></div></section>
  <section className="about-statement"><p className="eyebrow">My point of view</p><p>Build something real, make it explain itself, then make it strong enough to recover.</p></section>
  <section className="about-section journey-section"><div className="about-section-label"><span>01</span><h2>How I got here</h2></div><div className="journey-track"><div className="journey-line" />{timeline.slice().reverse().map((item, index) => <article className={`journey-node journey-node-${item.type} ${item.year === '2025' ? 'journey-node-current' : ''}`} key={`${item.year}-${index}`}><div className="journey-marker"><span>{String(index + 1).padStart(2, '0')}</span></div><div className="journey-card"><div className="journey-meta"><span>{item.year}</span><b>{item.type === 'education' ? 'BASE CAMP' : item.year === '2025' ? 'CURRENT RUN' : 'MISSION COMPLETE'}</b></div><h3>{item.title}</h3><p>{item.description}</p></div></article>)}</div></section>
  <section className="about-section"><div className="about-section-label"><span>02</span><h2>What I bring</h2></div><div className="capability-grid">{['Cloud architecture', 'Reliability & observability', 'DevSecOps delivery', 'Platform thinking'].map((title, index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{['Designing infrastructure that scales without becoming mysterious.', 'Turning telemetry into decisions teams can act on during incidents.', 'Shipping repeatable, secure delivery pipelines with clear guardrails.', 'Building tools that give engineers leverage, not another dashboard.'][index]}</p></article>)}</div></section>
  <section className="about-section"><div className="about-section-label"><span>03</span><h2>Working toolkit</h2></div><div className="skill-cloud">{skills.map((skill, index) => <span key={`${skill}-${index}`}><Check size={13} />{skill}</span>)}</div></section>
</main>

export default About