import { ArrowUpRight, MapPin, ShieldCheck, AlertTriangle, Search, Wrench } from 'lucide-react'
import { useState } from 'react'
import { Link } from 'react-router-dom'
import '../home-reference.css'

const Home = () => {
  const [activeIncident, setActiveIncident] = useState(0)
  const incidents = ['CrashLoopBackOff', 'OOMKilled', 'Kubernetes DNS failure', 'Database connection exhaustion', 'Latency spike']
  const timeline = ['REQUESTS', 'LATENCY SPIKE', 'ALERT', 'POD RESTARTS', 'INVESTIGATION', 'ROOT CAUSE', 'REMEDIATION', 'RECOVERY']

  return <main className="sre-home sre-desk-home">
    <div className="sre-home-shell">
      <section className="sre-main">
        <div className="desk-identity-strip"><span className="sre-monogram">DS</span><strong>Daksh Sawhney</strong><span>Cloud &amp; reliability engineer</span><span className="desk-location"><MapPin size={12} /> India</span><a href="/resume/Daksh-Resume.pdf" target="_blank" rel="noreferrer">Resume <ArrowUpRight size={12} /></a></div>
        <header className="control-hero"><div className="control-hero-copy"><p className="sre-kicker">Built for every curious mind / whatever your domain</p><h1>Cloud &amp; SRE Engineer<br /><em>building for failure.</em></h1><p>I teach multicloud systems and build useful things that run, from resilient infrastructure and automation to observability and self-healing platforms.</p><div className="control-hero-actions"><Link className="sre-primary" to="/projects">Explore the systems <ArrowUpRight size={16} /></Link><a className="sre-secondary" href="/resume/Daksh-Resume.pdf" target="_blank" rel="noreferrer">View resume <ArrowUpRight size={15} /></a></div><div className="control-stack">AWS <b>·</b> Azure <b>·</b> Kubernetes <b>·</b> Terraform <b>·</b> CI/CD <b>·</b> Prometheus <b>·</b> Grafana <b>·</b> Linux</div></div><div className="control-plane-visual"><div className="plane-header"><span><i /> RELIABILITY LAB / READY</span><span>BUILD → BREAK → RECOVER</span></div><div className="plane-flow">{['SIGNAL', 'ALERT', 'INVESTIGATE', 'DECIDE', 'RECOVER'].map((step, index) => <div key={step} className={index === 0 ? 'active' : ''}><span>{String(index + 1).padStart(2, '0')}</span><strong>{step}</strong></div>)}</div><div className="plane-footer"><span>telemetry → policy → runbook</span><b>SIMULATION / READY</b></div></div></header>
        <section className="impact-metrics"><p className="sre-kicker">Engineering outcomes</p><div><span><strong>40%</strong><small>P95 API latency reduction</small></span><span><strong>30%</strong><small>MTTR reduction</small></span><span><strong>70%</strong><small>Deployment-time reduction</small></span><span><strong>50K</strong><small>Concurrent users load tested</small></span><span><strong>5</strong><small>Reproducible failure scenarios</small></span></div></section>
        <section className="incident-zero" id="incident-zero"><div className="section-lead"><p className="sre-kicker">Featured lab / Incident Zero</p><h2>What happens when<br /><em>a system breaks?</em></h2><p>A failure simulation and response workflow for turning noisy signals into a documented recovery.</p></div><div className="incident-board"><div className="incident-board-head"><span><AlertTriangle size={15} /> INCIDENT ZERO / SIMULATED</span><span>RECOVERY PLAYBOOK</span></div><div className="incident-timeline">{timeline.map((step, index) => <span key={step} className={index <= 5 ? 'done' : ''}>{step}{index < timeline.length - 1 && <b>→</b>}</span>)}</div><div className="incident-board-foot"><span>Signal: request latency / service: simulated API</span><strong>RCA TEMPLATE READY</strong></div></div><div className="failure-modes">{incidents.map((incident, index) => <button key={incident} className={activeIncident === index ? 'active' : ''} onClick={() => setActiveIncident(index)}><AlertTriangle size={14} />{incident}</button>)}<div className="incident-detail"><span>ACTIVE FAILURE MODE</span><strong>{incidents[activeIncident]}</strong><p>Signal → detection → investigation → root cause → resolution → RCA</p></div></div></section>
        <section className="feedback-loop"><div className="section-lead"><p className="sre-kicker">How I think</p><h2>Reliability is a<br /><em>feedback loop.</em></h2></div><div className="loop-columns"><article><ShieldCheck size={22} /><h3>OBSERVE</h3><p>SLIs · SLOs · metrics · logs · alerts</p></article><article><Search size={22} /><h3>INVESTIGATE</h3><p>Incident response · correlation · Kubernetes events · RCA</p></article><article><Wrench size={22} /><h3>RECOVER</h3><p>Automation · remediation · runbooks · CI/CD</p></article></div></section>
        <section className="reliability-stack"><div className="section-lead"><p className="sre-kicker">Reliability stack</p><h2>Systems thinking,<br /><em>layer by layer.</em></h2></div><div className="stack-layers"><span><b>OPERATIONS</b>SLO · SLI · Incident Response · RCA · Runbooks · On-call</span><span><b>OBSERVABILITY</b>Prometheus · Grafana · CloudWatch</span><span><b>ORCHESTRATION</b>Kubernetes · EKS · AKS</span><span><b>INFRASTRUCTURE</b>Terraform · AWS · Azure · GCP</span><span><b>AUTOMATION</b>Python · Bash · GitHub Actions · CI/CD</span></div></section>
        <section className="on-call"><p className="sre-kicker">On-call mindset</p><h2>ALERT <b>→</b> VERIFY <b>→</b> SCOPE <b>→</b> CORRELATE <b>→</b> ROOT CAUSE <b>→</b> MITIGATE <b>→</b> DOCUMENT <b>→</b> PREVENT</h2></section>
      </section>
    </div>
  </main>
}

export default Home